### ISSUE TITLE
Приветствую!)

### ISSUE THREAD

**Issue by DJEHKNHC** [siarheidudko/hulk#1]
сижу сонный  никак не могу все правильно настроить:( хочется затестить сейчас но ручки не позволяют.Прошу помощи , может есть примеры уже заполненных скриптов куда только ссыль вставить надо?

буду очень благодарен если поможете=)

**Comment by siarheidudko** [comment]
Привет, видимо пропустил сообщение на почте.
Самый простой путь создать скрипт
test.js с содержимым

`var hulkCli = require('@sergdudko/hulk').cli;
hulkCli();`

После этого запустить nodejs с необходимыми параметрами (скорее всего, вам достаточно будет верхнего примера), где 99999 - общее количество запросов, 9999 - количество запросов в минуту.

`node test.js http://link.com GET 99999 9999

node test.js set_you_link set_this_data set_this_method set_req_total set_req_in_min

  - set_you_link - http://link.com
  - set_this_data - dsdsdsds
  - set_this_method - POST
  - set_req_total - 100
  - set_req_in_min - 1000 req/min`
